rtic-rs/cortex-m-rtic

src/lib.rs

`peripherals!` is the safe way to declare `Peripheral`s

hide the unsafe Peripheral::new constructor

---

examples/late-resources.rs
macros/src/trans.rs

it assumed that all resources were "early" resources

fix `idle::Resources::new`

---

.gitignore
Cargo.toml
examples/custom-type.rs
examples/full-syntax.rs
examples/generics.rs
examples/late-resources.rs
examples/one-task.rs
examples/preemption.rs
examples/safe-static-mut-ref.rs
examples/two-tasks.rs
macros/Cargo.toml
macros/src/analyze.rs
macros/src/check.rs
macros/src/trans.rs
src/lib.rs
tests/cfail/init-resource-share-idle.rs
tests/cfail/init-resource-share-task.rs
tests/cfail/lock.rs
tests/cfail/token-transfer.rs

safe `&'static mut` references via init.resources

---

Cargo.toml
ci/script.sh
src/lib.rs

closes #53
alternative solution to #54
depends on japaric/cortex-m#72

add a Cargo feature, cm7-r0p1, to fix a Cortex-M7 BASEPRI erratum

---

macros/src/codegen.rs
macros/src/syntax.rs

codegen/statics: forward #[cfg] attributes

---

ci/script.sh
src/lib.rs

impl Default for Duration

---

macros/src/codegen.rs

fix non_camel_case_types warnings

---

src/lib.rs

add Duration.as_cycles

---

book/en/src/by-example/tips.md
ci/expected/binds.run
ci/script.sh
examples/binds.rs
macros/src/check.rs
macros/src/codegen.rs
macros/src/syntax.rs
tests/cfail/used-free-interrupt-2.rs
tests/cpass/binds.rs

closes #128 
r? @korken89 or @TeXitoi 
suggestions for tests are welcome! (2 of the 3 tests I added hit bugs in my implementation)

implement RFC #128: #[interrupt(binds = ..)]

---

book/ru/src/by-example/tips.md

(ru) binds

---

book/en/src/by-example/types-send-sync.md
ci/script.sh
examples/shared-with-init.rs

book: note that late resources must be Send

---

macros/src/codegen.rs

only `static mut` resources need proxies
just a codegen optimization

generate resource proxies only when needed

---

macros/src/codegen.rs
src/export.rs
src/lib.rs

and stop newtyping `core::mem::MaybeUninit`
this also fixes CI on nightly

removes the maybe_uninit feature gate

---

macros/src/check.rs
tests/cfail/init-extra-late-resources.rs
tests/cfail/init-missing-late-resources.rs

that was added in #140 but it's no longer required
this PR also adds some cfail tests to test the updated code

remove unused check

---

Cargo.toml
ci/after-success.sh
macros/Cargo.toml
macros/src/lib.rs
redirect.html

this should build the latest docs and the docs for v0.4.x after successful merges

fix gh-pages build

---

CONTRIBUTING.md
README.md

Inspired by the Rust lang [CONTRIBUTING.md](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md), but small. There might be more we want to use from there.

add CONTRIBUTING.md and link to Matrix room

---

macros/src/codegen.rs

**HEADS UP** this PR targets the branch v0.4.x

[backport] unlock the DWT, if locked, when using the timer queue

---

book/en/src/by-example/tips.md
examples/destructure.rs

As per last meeting, a bare-bones added that we can improve

Added struct de-structure-ing example in tips & tricks

---

book/en/src/preface.md

[v0.4.x] book: fix link to API

---

CHANGELOG.md
Cargo.toml

Preparing for v0.4.4 release

---

Cargo.toml
examples/schedule.rs

instead of a unsafe write_volatile call

use the safe DWT::unlock API

---

book/en/src/by-example/app.md

Reference the correct example in the by-example book

---

macros/src/custom_local.rs

Remove dependency on analyze
Indicate for all occurrences of lock free resources where error occurs.

Fix lock_free error reporting

---

.travis.yml
ci/install.sh

Instead of building mdbook, get a precompiled version

Use statically compiled mdbook

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/properties/build.properties.json
.github/workflows/properties/docs.properties.json
.github/workflows/properties/publish.properties.json
.github/workflows/publish.yml

Implementing previous Travis CI setup on Github Actions

Testing GHA v0.1

---

examples/t-cfg-resources.rs
macros/src/codegen.rs
macros/src/codegen/init.rs
macros/src/codegen/post_init.rs

Fix style issues reported by cargo fmt

Run cargo fmt

---

Cargo.toml
macros/src/codegen.rs
src/lib.rs

do not optimize build deps

---

.github/workflows/build.yml
examples/peripherals-taken.rs
macros/src/codegen/pre_init.rs

Fixes an issue where one could double take the cortex_m Peripheral

---

README.md

Badges for quick access to the corresponding pages on **crates.io**, **docs.rs**, the **book** (aka **rtic.rs**), as well as a badge for showing the **minimum required rustc version**.

Added badges to 'README.md' file

---

macros/src/codegen/pre_init.rs

Potential fix for #351
Introduced by #338

Reuse cortex-m

---

examples/binds.rs
examples/cfg.rs
examples/hardware.rs
examples/idle.rs
examples/resource.rs
examples/t-cfg-resources.rs
examples/t-cfg.rs
examples/t-idle-main.rs
examples/t-late-not-send.rs
examples/t-resource.rs
examples/t-schedule.rs
examples/t-spawn.rs
examples/types.rs

Fixed so examples do not crash in release mode

---

book/en/src/by-example/app.md
book/en/src/by-example/new.md
book/en/src/by-example/resources.md
book/en/src/by-example/tasks.md
book/en/src/by-example/tips.md

close console text blocks on a new line

---

.github/workflows/build.yml

Test to see if latest mdBook works with current formatting, see #369

Use latest mdBook

---

book/en/src/by-example.md

Added a real world example for my sandbox project.

add sandbox example

---

book/en/src/by-example/app.md
book/en/src/by-example/new.md

feel free to nitpick path terminology

device path must be absolute; clarify

---

CHANGELOG.md

Updating the changelog

---

CHANGELOG.md
book/en/src/migration/migration_v5.md
examples/extern_binds.rs
examples/extern_spawn.rs
macros/src/codegen/hardware_tasks.rs
macros/src/codegen/software_tasks.rs
ui/single/extern-interrupt-used.rs

Allows hardware and software task to be externally declared.
CI test, don't merge yet (squash needed).

Extern task

---

book/en/book.toml
book/en/src/by-example/app.md

book.toml/by-example/app

---

book/en/src/by-example/new.md

Fixup app/new

---

examples/task_named_main.rs
macros/src/codegen.rs

Prevents conflict with user provided tasks named main
Curious what the full test suite will make of this

Move entry-point main into a separate module

---

.github/workflows/build.yml
ui/single/locals-cfg.stderr
ui/single/resources-cfg.stderr

Try fixing GHA by removing the ci-failure job
[Related change in Bors](https://github.com/bors-ng/bors-ng/issues/1129)

Remove GHA ci-failure job

---

book/en/src/by-example/types-send-sync.md

Minor grammar correction

---

.github/workflows/build.yml

Same as done in https://github.com/rtic-rs/cortex-m-rtic/commit/fa2de97d870e0476cd7a0107193ae426ef8c3997

Fix GHA by removing duplicate CI-check

---

README.md

Want to try GH-pages rebuild by GHA

Tiny fix of README-link

---

.github/workflows/build.yml

As suggested in https://github.com/rtic-rs/rfcs/pull/48#issuecomment-815730654

Force push to gh-pages branch

---

README.md
book/en/src/by-example/tips.md

Add links to RTIC book dev version and rtic-examples

---

macros/src/codegen/module.rs

More rustanalyzer lint fixes

---

src/lib.rs

To document the feature from PR #509.

Update rust-doc text on lib.rs to document `cortex-m-7` feature

---

book/en/src/awesome_rtic.md
book/en/src/by-example.md
book/en/src/by-example/app.md
book/en/src/by-example/app_idle.md
book/en/src/by-example/app_init.md
book/en/src/by-example/app_priorities.md
book/en/src/by-example/app_task.md
book/en/src/by-example/hardware_tasks.md
book/en/src/by-example/message_passing.md
book/en/src/by-example/monotonic.md
book/en/src/by-example/resources.md
book/en/src/by-example/software_tasks.md
book/en/src/by-example/starting_a_project.md
book/en/src/by-example/tips_destructureing.md
book/en/src/by-example/tips_from_ram.md
book/en/src/by-example/tips_indirection.md
book/en/src/by-example/tips_monotonic_impl.md
book/en/src/by-example/tips_static_lifetimes.md
book/en/src/by-example/tips_view_code.md
book/en/src/migration.md
book/en/src/migration/migration_v4.md
book/en/src/migration/migration_v5.md
book/en/src/preface.md

Unleashed some language linters on the book

Docs touchup

---

CHANGELOG.md
ci/expected/periodic-at.run
ci/expected/periodic-at2.run
examples/periodic-at.rs
examples/periodic-at2.rs

Examples on drift free usage under RTIC 1.0.

Spawn at periodic

---

book/en/src/by-example/monotonic.md

Run the right examples in chapter 1.5.5 in the book

Fix running command examples in chapter 1.5.5 Monotonic

---

CONTRIBUTING.md

Split out from Per’s previous work in `lockall` branch with some minor updates

CONTRIBUTION.md now includes CI prep.

---

book/en/src/by-example/hardware_tasks.md
book/en/src/by-example/software_tasks.md

Reword and (hopefully) clarify SW and HW tasks
Closes #576

Docs: SW and HW tasks

---

.github/workflows/build.yml
CHANGELOG.md
macros/src/codegen/module.rs
macros/src/codegen/software_tasks.rs
macros/src/codegen/util.rs
src/tq.rs

- GHA: Use rust-cache
- GHA: Cleanup single target jobs
- GHA: Add cargo clippy

GHA: Tune CI

---

CHANGELOG.md
ci/expected/complex.run
examples/complex.rs
macros/src/codegen.rs
macros/src/codegen/assertions.rs
macros/src/codegen/shared_resources.rs
macros/src/codegen/util.rs
src/export.rs
ui/v6m-interrupt-not-enough.rs_no

This is an experimental implementation of SRP based scheduling on the M0/M0+ (thumbv6m) architecture. 
The aim is a (sub)-zero abstraction to the resource protection (locking mechanism).
Please try, but not merge yet, since its an early POC.

Fine grained concurrency on thumbv6m (no BASEPRI).

---

CHANGELOG.md
Cargo.toml
macros/Cargo.toml

Bump versions, including using using latest rtic-syntax

Release RTIC v1.1

---

CHANGELOG.md
macros/src/codegen/shared_resources.rs
macros/src/codegen/util.rs
src/export.rs

This solves the `MASKS` generation issue by having `rtic::export` do the feature gating.

Masks take 3

---

macros/src/codegen/pre_init.rs
ui/task-priority-too-high.stderr

More ergonomic error from static asserts messages

---

macros/Cargo.toml
macros/src/codegen/assertions.rs
macros/src/codegen/pre_init.rs
src/export.rs

Fix clash with defmt

---

.github/dependabot.yml

dependabot: set "skip-changelog" label

---

book/en/src/SUMMARY.md
book/en/src/by-example/starting_a_project.md
book/en/src/internals/targets.md

Most of the RTIC documentation focuses on ARMv7-M architectures. Here's some initial thoughts on useful information I would have liked to know before starting with RTIC on ARMv6-M.

Add documentation for different Cortex-M architectures

---

book/en/src/internals/targets.md

Looks like the unicode didn't render properly, Here's the fix.

Fix Unicode ✓

---

CHANGELOG.md
book/en/src/by-example/app_init.md
book/en/src/by-example/app_priorities.md
book/en/src/by-example/app_task.md
book/en/src/by-example/hardware_tasks.md
book/en/src/by-example/monotonic.md
book/en/src/by-example/resources.md
book/en/src/by-example/software_tasks.md
book/en/src/by-example/starting_a_project.md
book/en/src/by-example/tips_indirection.md
book/en/src/by-example/tips_monotonic_impl.md
book/en/src/by-example/tips_static_lifetimes.md
book/en/src/migration/migration_v5.md

Continuation of https://github.com/rtic-rs/cortex-m-rtic/pull/618
Better late than never...
A big thanks to @jvanderk !

Book: Editorial review

---

CHANGELOG.md
examples/cfg-monotonic.rs
examples/cfg-whole-task.rs
macros/src/codegen.rs
macros/src/codegen/assertions.rs
macros/src/codegen/hardware_tasks.rs
macros/src/codegen/module.rs
macros/src/codegen/post_init.rs
macros/src/codegen/pre_init.rs
macros/src/codegen/shared_resources_struct.rs
macros/src/codegen/software_tasks.rs
macros/src/codegen/timer_queue.rs

CFG: Support HW tasks, cleanup for SW tasks
