rtic-rs/cortex-m-rtic

.travis.yml
build.rs
ci/install.sh
ci/script.sh
src/lib.rs

simplify the tasks! macro, make the `request` function more straightforward

---

Cargo.toml
src/lib.rs
tests/cfail/claim_mut.rs

to assert that they point to `static` data

wrap references to resources in static-ref's Ref/RefMut

---

src/lib.rs
tests/cfail/access.rs
tests/cfail/ceiling.rs
tests/cfail/lock.rs
tests/cfail/peripherals-alias-2.rs
tests/cfail/race-1.rs
tests/cfail/race-2.rs
tests/cfail/tasks-p0.rs
tests/cfail/tasks-same-handler.rs
tests/cfail/tasks-wrong-ceiling.rs
tests/cfail/tasks-wrong-idle.rs
tests/cfail/tasks-wrong-init.rs
tests/cfail/tasks-wrong-task.rs

remove the P.as_ceiling method

make the ceiling part of the task signature

---

src/lib.rs

with svd2rust 0.8.x peripheral types are written in UPPERCASE and match their
names so specifying the type in the register_block field is no longer necessary.
depends on japaric/svd2rust#85 and a new svd2rust release

make the register_block field optional in the peripherals! macro

---

.cargo/config
Cargo.toml
ci/install.sh
examples/late-resources.rs
macros/Cargo.toml
macros/src/trans.rs
src/lib.rs
tests/cfail.rs
tests/cfail/late-resource-init.rs
tests/cfail/wrong-threshold.rs

Closes #37 
TODO:
* Figure out why I cannot run these tests

Allow initialization of resources in `init`.

---

Cargo.toml
examples/generics.rs
examples/one-task.rs
examples/zero-tasks.rs
macros/src/check.rs
macros/src/trans.rs
src/lib.rs

See this RFC for details: japaric/svd2rust#157
- The first commit adapts this crate to the changes in japaric/cortex-m#65 and japaric/svd2rust#158
- ~~The second commit is an alternative implementation of RFC #47 (there's another implementation in #49. This second commit is not required for RFC157 but let us experiment with safe DMA abstractions.~~ postponed
~~This depends on PR japaric/rtfm-syntax#2~~ postponed

Peripherals as scoped singletons

---

examples/generics.rs
examples/late-resources.rs
macros/src/trans.rs
src/examples/_5_late_resources.rs
tests/cfail/late-resource-init.rs

After writing `LateResourceValues` several times I now think it's too long to type. I'd like that
struct to be renamed to `LateResources`. I don't think there would be a loss in readability with the
rename because you can think of "late resources" as resources that "don't exist" until `init` ends
instead of as resources that are not initialized after `init` ends -- the second meaning maps better
to `LateResourceValues`.
This would be a breaking-change but we are moving to v0.3.0 due to #50 in any case.
cc jonas-schievink

[RFC] rename LateResourceValues to LateResources

---

Cargo.toml

this seems to be required for cargo publish to Just Work
cc @jonas-schievink

specify both the path and version of the cortex-m-rtfm-macros dependency

---

Cargo.toml
macros/Cargo.toml
macros/src/codegen.rs

`export_name` creates external symbols that won't be removed when using `-Z
emit-stack-sizes`

codegen: stop using `export_name`

---

CHANGELOG.md
src/lib.rs

```
<eddyp> japaric: is https://docs.rs/cortex-m-rtfm/book/ supposed to be a "dead" link?
* peri_ (peri@moz-c2q.111.74.96.IP) has joined
* peri_ has quit (Connection closed)
<japaric> eddyp: yes, the correct URL is https://japaric.github.io/cortex-m-rtfm/book/ ; does something link to docs.rs/*/book?
japaric Jackneill Jacob_____ jamesmunns jasper jayaura 
* peri has quit (Connection closed)
* peri_ (peri@moz-c2q.111.74.96.IP) has joined
<eddyp> japaric: https://docs.rs/cortex-m-rtfm/0.4.0/rtfm/ 
<eddyp> probably relative link?
<eddyp> at "The user level documentation can be found here."
<japaric> eddyp: probably. If you want to score some GH points you can send a PR to make the url absolute
japaric Jackneill Jacob_____ jamesmunns jasper jayaura 
<eddyp> japaric: I can do it tomorrow since …
```

Absolute link to the book so it works on crates.io

---

CHANGELOG.md
Cargo.toml
book/en/src/by-example/resources.md
book/ru/src/preface.md
examples/late.rs
examples/singleton.rs
examples/static.rs
macros/src/check.rs
macros/src/codegen.rs
macros/src/syntax.rs
src/lib.rs
tests/cfail/early-return-2.rs
tests/cfail/early-return.rs
tests/cfail/init-divergent.rs
tests/cfail/init-input.rs
tests/cfail/init-output.rs
tests/cfail/late-not-send.rs
tests/cfail/late-uninit.rs
tests/cpass/late-not-send.rs
tests/cpass/late-resource.rs

TL;DR
1. v0.4.1 will be published once this PR lands
2. v0.4.0 will be yanked once v0.4.1 is out
3. v0.4.1 will reject code that contains early returns in `init` *and* contains
late resources. Yes, this is a breaking change but such code is unsound /
has undefined behavior.
4. as of v0.4.1 users are encouraged to use `fn init() -> init::LateResources`
instead of `fn init()` when they make use of late resources.
---
This PR fixes a soundness issue reported by @RalfJung. Basically, early
returning from `init` leaves *late resources* (runtime initialized statics)
uninitialized, and this produces undefined behavior as tasks rely on those
statics being initialized. The example below showcases a program that runs into
this soundness issue.
``` rust
#[rtfm::app(device = lm3s6965)]
const APP: () …
```

fix soundness issue: forbid early returns in init

---

.gitignore
.travis.yml
ci/script.sh
macros/src/analyze.rs
macros/src/check.rs
macros/src/codegen.rs
macros/src/syntax.rs
src/export.rs
tests/compiletest.rs

This is a rebased and augmented version of #132. With this PR both dev and release builds that do not use the owned-singleton stuff become reproducible. (I haven't really bothered to make owned-singleton reproducible since [lifo] is way more ergonomic than [alloc-singleton] and will eventually make its way into heapless).
[lifo]: https://github.com/japaric/lifo
[alloc-singleton]: https://crates.io/crates/alloc-singleton
Thanks @hugwijst for doing the bulk of the work!
closes #132

make builds reproducible

---

Cargo.toml
ci/script.sh
macros/Cargo.toml
macros/src/codegen.rs
src/export.rs
src/lib.rs

this implements the action plan described in #149
to give you a sense of the overhead of this change: it has increased the binary
size of some of our examples by up to 10% but this is mainly from pulling in a
panic handler that does formatting
r? @korken89

add "nightly" feature; replace hint::unreachable_unchecked with a panic

---

macros/src/syntax.rs
tests/cfail/duplicate-args-2.rs
tests/cfail/duplicate-args.rs

This program was being accepted:
``` rust
#[task(
capacity = 1,
capacity = 2,
priority = 1,
priority = 2,
)]
fn foo() {}
```
now it will trigger a compiler error
r? @korken89 || @TeXitoi

reject duplicate arguments in #[interrupt] and #[exception]

---

book/en/src/by-example/resources.md
macros/src/codegen.rs
macros/src/syntax.rs
tests/cfail/priority-too-high.rs
tests/cfail/priority-too-low.rs

before we were checking the priority at runtime. The compile time error message
when the priority is too high is kind of awful though.

check task priority at compile time

---

.travis.yml
macros/src/analyze.rs

This commit fixes a ceiling bug where the ceiling of a ready queue will be
incorrectly computed. The analysis was not including the priority of the system
timer interrupt (`SysTick`) in the analysis resulting in a priority ceiling
lower than what's required for memory safety which led to data races.
The bug can be observed in the following program:
``` rust
#[rtfm::app(device = /* .. */)]
const APP: () = {
#[init]
fn init() {
// ..
}
#[task(priority = 2)]
fn foo(x: i32) {
// ..
}
#[task(priority = 1, spawn = [foo], schedule = [foo])]
fn bar() {
// ..
}
extern "C" {
fn EXTI0();
fn EXTI1();
}
};
```
Here the framework chooses a priority of `2` for the `SysTick` interrupt
(because it matches the priority of the `schedule`-able task `foo`).
Both `SysTick` and `bar::Spawn.foo` need to access …

backport: fix ceiling analysis bug

---

Cargo.toml
ci/script.sh
macros/Cargo.toml
macros/src/codegen.rs
src/export.rs

with the upcoming version of heapless we are able to initialize all internal
queues in const context removing the need for late initialization
this commit also removes the "nightly" feature because all the optimization
provided by it are now enabled by default

bump heapless dependency to v0.5.0; remove "nightly" feature

---

macros/src/codegen.rs

On cold boot, the DWT unit is off, which means our attempts to clear and
disable the cycle counter in pre-init don't work. This seems to result
in access to CYCCNT always returning 1073741824, which delays tasks
scheduled in init by that many cycles (~15s at 72 MHz).
Fixes #196.

Enable the DWT unit before poking at its registers. (v0.4.x)

---

Cargo.toml
macros/Cargo.toml

required for publishing v0.5.0-beta

turn git deps into crates.io deps

---

README.md

Fix the matrix.to link so that the room history can be viewed in
"Matrix-Static" by users who aren't registered on Matrix (e.g. for
previewing).  Hopefully this will also get the room content into search
engines.
n.b. The new matrix.to URL uses the room name instead of the room ID,
because the ID didn't work with Matrix-Static, and the matrix.to README at:
https://github.com/matrix-org/matrix.to says...
"Note that linking to rooms by ID should only be used for rooms to which
the target user has been invited: these links cannot be assumed to work for
all visitors."

Fix matrix.to web link for the static room view.

---

CHANGELOG.md
Cargo.toml
LICENSE-MIT
book/en/src/by-example.md
book/en/src/by-example/new.md
ci/install.sh
macros/Cargo.toml

this updates all the remaining references to japaric/cortex-m-rtfm, the Cargo metadata and copyright notice. After this PR the crates will be ready for beta release.

v0.5.0 beta release

---

book/en/src/internals/critical-sections.md

Fixing what was probably a copy-paste error; different tasks each have different types for their context.

critical sections book: each task gets its own context

---

CHANGELOG.md
book/en/src/by-example/timer-queue.md
examples/baseline.rs
examples/periodic.rs
examples/schedule.rs
src/cyccnt.rs
src/lib.rs

covers
- initialization and configuration of the timer; this is now a responsibility of
the application author
- correctness of `Monotonic::now()` in `#[init]`
- safety of `Monotonic::reset()`
closes #251
cc @jonas-schievink
(EDIT: yay, pull request number 0xFF)

more monotonic timer docs

---

macros/src/codegen/resources.rs

this is done using the `.uninit` linker section; this optimization was already
being applied to message buffers but I forgot to also apply it to late resources

do not zero late resource memory on boot

---

.travis.yml

The docs for the v0.4.x releases are now being built and uploaded by the master
branch
addresses #262

[v0.4.x] CI: do not build docs

---

ci/after-success.sh

instead of using a specific tag; this way documentation changes done to the
v0.4.x branch will show up on the site as soon as they land -- right now they
require publishing a new v0.4.x release on crates.io

CI: build 0.4 docs from the v0.4.x branch

---

.cargo/config
.travis.yml
Cargo.toml
ci/script.sh
tests/single.rs
ui/single/exception-invalid.stderr
ui/single/exception-systick-used.stderr
ui/single/extern-interrupt-not-enough.stderr
ui/single/extern-interrupt-used.stderr
ui/single/locals-cfg.stderr
ui/single/resources-cfg.stderr
ui/single/task-priority-too-high.stderr

We use compiletest to run compile-fail tests but compiletest depends on compiler
internals so it breaks every now and then and requires nightly. With trybuild we
can also run compile-fail tests but it works on stable and it already has
reached version 1.0

CI: replace compiletest-rs with trybuild

---

.travis.yml
ci/install.sh

to workaround compiletest-rs being broken on recent nightlies
this is a backport of #267 and it's required to land #265 
I'm not backporting #268  (compiletest -> trybuild) because this branch has compile-pass tests which depend on compiletest and can't be ported to trybuild

[v0.4.x] CI: pin to an older nightly

---

src/tq.rs

ARM Architecture Reference Manual says: "Setting SYST_RVR to zero has the effect of disabling the SysTick counter independently of the counter enable bit."
If Monotonic's ratio is less than one, the timeout calculations
can compute zero if next task is scheduled after current instant, but
before next timer tick. This results in disabling SYST and freezing the
timer queue.
The division by ratio's denominator rounds downward and the dequeue
condition is `if instant < now`. If ratio is small enough, this results
in unnecessary interrupts:
Let's say `instant - now` is 99 and ratio is 1/25. Then, `dur` will
equal 3 and the next tick will happen at `now + 75`. In the next
interrupt, `instant > now` and additional tick needs to be scheduled
(which doesn't happen, because now `instant - now` is …

TimerQueue.dequeue: don't set SYST reload to 0

---

book/en/src/migration.md

Makes note of the fact the DWT has to be enabled manually in rtfm 0.5.0; an easy one to miss considering debuggers generally enable the DWT automatically.

Include DWT enable in migration guide

---

book/ru/src/by-example/app.md

Fix typo in Russian translation of book, was "When idle function is declared", should be "When no idle function is declared"
"не" means "not".
Corresponding text in English:
```markdown
When no `idle` function is declared, the runtime sets the [SLEEPONEXIT] bit and
then sends the microcontroller to sleep after running `init`.
```

book, Russian lang: fix "idle not defined" typo

---

Cargo.toml
build.rs
ci/script.sh

Extend the current test suite to allow for running tests on newer rustc-versions than current MSRV.
Required by #306 to add special tests for future MSRV.
To exclude an example from the regular non-nightly testing:
```
#![no_main]
#![no_std]
#[cfg(rustc_is_nightly)]
mod example {
use panic_halt as _;
#[rtfm::app(device = lm3s6965)]
const APP: () = {
<more code>
}
}
```

Use build.rs for conditional compilation

---

examples/t-cfg-resources.rs
macros/src/codegen.rs
macros/src/codegen/init.rs
macros/src/codegen/post_init.rs
macros/src/codegen/resources.rs

When rust 1.43 lands as stable this will resolve #301 and allow for the kind of conditional compilation exemplified in the issue.
Tested on beta and nightly.

Retain cfg-attributes on resources

---

.github/workflows/build.yml
ci/script.sh

#314 is failing the tests since 1.36.0 is not capable of 'build-override' profiles.
This extends current CI setup for both Travis and GHA to remove any `build-override` before running in case toolchain is 1.36.0.

No build opt on msrv

---

.github/workflows/build.yml
Cargo.toml
ci/script.sh
examples/t-cfg-resources.rs

As noted by japaric, using cargo features to do selective testing is cleaner than cfg-hacks.
Introduce new testing-feature indicating this test requires at minimum Rust v1.43.
Modify both test-suites to handle the new feature and remove the cfg-hack from the example.

Use cargo feature instead of conditional compilation hacks

---

examples/t-htask-main.rs
examples/t-idle-main.rs
examples/t-init-main.rs
examples/t-stask-main.rs
macros/src/codegen/dispatchers.rs
macros/src/codegen/idle.rs
macros/src/codegen/init.rs

`#[init]`, `#[idle]` and `#[task]` handlers can now be named `main`
fixes #311

allow handlers to be named 'main'

---

examples/periodic.rs

The example above this in the documentation states
```
// semantically, the monotonic timer is frozen at time "zero" during `init`
// NOTE do *not* call `Instant::now` in this context; it will return a nonsense value
let now = cx.start; // the start time of the system
```
It results in weird scheduling issues, but still eventually works.  `cx.start` is much more reliable.
Relates to https://github.com/rtfm-rs/cortex-m-rtfm/issues/196

Update example to use better initial value

---

examples/baseline.rs
examples/capacity.rs
examples/cfg.rs
examples/message.rs
examples/not-send.rs
examples/not-sync.rs
examples/periodic.rs
examples/pool.rs
examples/schedule.rs
examples/t-cfg.rs
examples/t-schedule.rs
examples/t-spawn.rs
examples/t-stask-main.rs
examples/task.rs
examples/types.rs

Some beginners are confused about the "extern" section, so I added an explanation comment to all examples.
Furthermore, using the UARTx interrupts when UART is actually being used in the same example may be confusing, so I changed them all to SSI0/QEI0.

Examples: Clarify extern section

---

book/en/src/by-example/new.md

(the file at tag '0.5.0' still uses `rtfm`, rather than `rtic` from tag '0.5.3' or later)

Updated URL for example 'init.rs' file

---

.github/workflows/build.yml

Using [GHA caching](https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows) to store key parts of the testing environment.
One example is downloading `arm-none-eabi-gcc` (which takes roughly 1 minute) for each checkexamples.
The rustup setup is roughly 200MB and restores nicely.
Rust examples can be found [here](https://github.com/actions/cache/blob/master/examples.md#rust---cargo)
**Something to discuss:**
Several notable projects remove some problematic files in order to keep cache size reasonable
[rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/blob/9a7db8fa009c612168ef16f6ed72315b5406ed09/.travis.yml#L2-L4)
[cargo duscussion](https://github.com/rust-lang/cargo/issues/5885) …

Enable caching for Github Actions

---

.github/workflows/build.yml

There seems to be issues when Rust 1.45 is upgraded to 1.46.
```
[command]/usr/share/rust/.cargo/bin/rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/runner/.rustup
stable-x86_64-unknown-linux-gnu (directory override for '/home/runner/work/cortex-m-rtic/cortex-m-rtic')
rustc 1.45.2 (d3fb005a3 2020-07-31)
[command]/usr/share/rust/.cargo/bin/rustup toolchain install stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-08-27, rust version 1.46.0 (04488afe3 2020-08-24)
info: downloading component 'clippy'
info: downloading component 'rustfmt'
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: removing previous version of component 'clippy'
info: removing …
```

Rust toolchain cache breaking on version change

---

.github/workflows/build.yml

This will currently fail similarly like in #364 which affects all examples using schedule
But this is required to fully check all examples.

Also check examples which require __v7

---

.github/workflows/build.yml

With the old 1.36.0 tests removed the full 20 free concurrent GHA jobs are not fully utilized.
Separate the run-pass testing and the cargo check of examples

Separate example check and run-pass tests

---

macros/src/codegen.rs
macros/src/codegen/pre_init.rs
macros/src/codegen/spawn_body.rs
macros/src/codegen/timer_queue.rs
macros/src/codegen/util.rs
ui/single/locals-cfg.stderr

This stops RTIC applications from compiling if one has forgotten to set the `rt` flag in the PAC/HAL.
The error:
```
error[E0433]: failed to resolve: could not find `interrupt` in `you_must_enable_the_rt_feature_for_the_pac_in_your_cargo_toml`
--> src/main.rs:8:1
|
8 | #[rtic::app(device = stm32l4xx_hal::pac)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `interrupt` in `you_must_enable_the_rt_feature_for_the_pac_in_your_cargo_toml`
|
= note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Detect if the rt flag is defined in the PAC/HAL

---

examples/cfg-whole-task.rs
macros/src/codegen/module.rs

Applying a `#[cfg(never)]` on a task:
before:
```
#[allow(non_snake_case)]
#[doc = "Software task"]
pub mod foo2 {
#[doc(inline)]
pub use super::foo2Resources as Resources;
#[doc = r" Execution context"]
pub struct Context<'a> {
#[doc = r" Resources this task has access to"]
pub resources: Resources<'a>,
}
impl<'a> Context<'a> {
#[inline(always)]
pub unsafe fn new(priority: &'a rtic::export::Priority) -> Self {
Context {
resources: Resources::new(priority),
}
}
}
<...>
```
After:
```
#[allow(non_snake_case)]
#[cfg(never)]
#[doc = "Software task"]
pub mod foo2 {
#[doc(inline)]
pub use super::foo2Resources as Resources;
#[doc = r" Execution context"]
pub struct Context<'a> {
#[doc = r" Resources this task has access to"]
pub resources: Resources<'a>,
}
impl<'a> Context<'a> { …
```

Add the cfgs on a task to the module for that task

---

.github/workflows/build.yml
Cargo.toml
book/en/src/preface.md
examples/not-send.rs
examples/not-sync.rs
examples/schedule.rs
examples/shared-with-init.rs
examples/t-binds.rs
examples/t-cfg-resources.rs
examples/t-cfg.rs
examples/t-late-not-send.rs
examples/t-resource.rs
examples/t-schedule.rs
examples/t-spawn.rs
ui/single/locals-cfg.stderr
ui/single/task-priority-too-high.rs
ui/single/task-priority-too-high.stderr

Tests are broken as of now with error message:
```
Run peaceiris/actions-mdbook@v1.1.11
mdbook version: 0.3.1
Operating System: unknown-linux-gnu
toolURL: https://github.com/rust-lang/mdBook/releases/download/v0.3.1/mdbook-v0.3.1-x86_64-unknown-linux-gnu.tar.gz
Error: Unable to process command '::add-path::/home/runner/toolbin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/tmp -f …
```

Fix the CI tests by using latest mdbook

---

Cargo.toml

RTIC may be flagged by cargo audit since it depends on heapless 0.5.x.
That is because heapless <= 0.6.1 depends on generic-array with a [security issue](https://github.com/RustSec/advisory-db/pull/789)
UB bug as discussed here: https://github.com/japaric/heapless/issues/181 is also resolved in 0.6.1.

Bump required version of heapless to 0.6.1

---

.github/workflows/audit.yaml
.github/workflows/properties/audit.properties.json

With the recent generic-array issue affecting heapless it seems wise to stay up to date with the latest advisories.

Add periodic GHA job to run cargo audit

---

examples/t-schedule.rs
examples/type-usage.rs
macros/Cargo.toml
macros/src/codegen.rs
macros/src/codegen/hardware_tasks.rs
macros/src/codegen/module.rs
src/tq.rs

Type aliases such as the following did not work in `0.6-alpha`:
```rust
use rtic::app;
#[app(device = lm3s6965, dispatchers = [SSI0])]
mod app {
type Test = u32;
#[task]
fn t1(_: t1::Context, _val: Test) {}
}
```
Plus that accessing associated constants of monotonic timers was not working as it should dues to the syntax and codegen transforming:
```rust
#[monotonic(binds = SysTick, default = true)]
type MyMono = DwtSystick<8_000_000>; // 8 MHz
```
into
```rust
mod MyMono {
// ...
}
```
causing the original `type MyMono` to not exist anymore.
This PR fixes this and adds test to check for this by doing the following expansion instead:
```rust
#[monotonic(binds = SysTick, default = true)]
type MyMono = DwtSystick<8_000_000>; // 8 MHz
```
into
```rust
type MyMono = DwtSystick<8_000_000>;
mod …
```

Fix for type aliases in `mod app`, UB in `spawn_at`, and `#[cfg]` in hardware tasks

---

macros/src/codegen.rs

Fixes #474.
Tested that there is no longer any stack overhead leftover from moving init resources.
(made mistake force pushing with last PR when trying to fix lint)
The expansion for an example with 2 buffers as resources changes from:
```rust
let (late, mut monotonics) = crate::APP::init(init::Context::new(core.into()));
__rtic_internal_mybuffer.as_mut_ptr().write(late.mybuffer);
__rtic_internal_mybuffer2.as_mut_ptr().write(late.mybuffer2);
rtic::export::interrupt::enable();
crate::APP::idle(idle::Context::new(&rtic::export::Priority::new(0)))
```
to:
```rust
#[inline(never)]
fn __rtic_init_resources<F>(f: F)
where
F: FnOnce(),
{
f();
}
__rtic_init_resources(|| {
let (late, mut monotonics) = crate::APP::init(init::Context::new(core.into())); …
```

reclaim stack space used in late init

---

book/en/src/by-example/app.md

As per the title. The required signature of `#[init]` in the flowing text has not yet been updated for v0.6.0.

book: update outdated required init signature

---

book/en/src/migration/migration_v5.md

From the comment in #478.
The example now migrates from v5 to v6 instead of an incorrect v6 syntax
to a another incorrect v6 syntax.

book/migration/v5: update init signature, fix example syntax

---

book/en/src/migration/migration_v5.md

That is, answering the question of why imports are no longer resolving during compilation.

book: detail import resolving for 0.6 migration

---

macros/src/codegen.rs
macros/src/codegen/dispatchers.rs
macros/src/codegen/locals.rs
macros/src/codegen/module.rs
macros/src/codegen/post_init.rs
macros/src/codegen/pre_init.rs
macros/src/codegen/resources.rs
macros/src/codegen/resources_struct.rs
macros/src/codegen/software_tasks.rs
macros/src/codegen/timer_queue.rs
src/lib.rs

Squashed and updated version of @perlindgren branch.
In release there are 0 bytes difference for all examples :tada: 
For debug we see a bloat of ~1-2% worst case, commonly less.
Complete diff of sizes for all examples (first is goodbye static mut, second is master):
```
<   27220	      0	     28	  27248	   6a70	spawn
---
>   27092	      0	     28	  27120	   69f0	spawn
<   16916	      0	     44	  16960	   4240	late
---
>   16836	      0	     44	  16880	   41f0	late
<   15952	      0	     12	  15964	   3e5c	type-usage
---
>   15872	      0	     12	  15884	   3e0c	type-usage
<   22068	      0	     44	  22112	   5660	cfg
---
>   21812	      0	     44	  21856	   5560	cfg
<   34784	      0	     40	  34824	   8808	periodic
---
>   34496	      0	     40	  34536	   86e8	periodic
<   22308	      0 …
```

Goodbye static mut

---

src/linked_list.rs

If one configures a monotonic in alpha4, but doesn't use it, TimerQueue attempts to create a zero-sized LinkedList, which causes an underflow.
This PR allows for zero-sized linked lists.

Allow zero sized LinkedList

---

book/en/src/migration/migration_v5.md

Minor problem with a minor fix.

Fix syntax error in migration guide

---

macros/src/codegen.rs
macros/src/codegen/pre_init.rs
macros/src/codegen/spawn_body.rs
macros/src/codegen/timer_queue.rs
macros/src/codegen/util.rs

NOTE: this is pull request against v0.5.x, not the main branch
what the title says: this backports the detection mechanism that tells you to enable the "rt" feature of the PAC when you forget to enable it

backport: "you must enable the rt feature" compile time detection

---

book/en/src/migration/migration_v5.md
examples/smallest.rs
examples/spawn.rs
examples/spawn2.rs
macros/src/tests/single.rs
ui/exception-invalid.rs
ui/extern-interrupt-not-enough.rs
ui/extern-interrupt-used.rs
ui/task-priority-too-high.rs

to use the new resources syntax
I also reordered the sections to cover all the resource API first before covering the spawn API
I've also added a section about the old `static mut` variable transform

update the 0.5.x -> 0.6.0 migration guide

---

book/en/src/by-example/resources.md
ci/expected/lock-free.run
ci/expected/resource.run
examples/lock-free.rs
examples/resource.rs

see individual commit messages for details.
what's still left to do is adjust the very last section about `#[task_local]` and `#[lock_free]` but I plan to do that as a follow up. I didn't find an in-tree example for those two attributes (are they field attributes? where do they fit in the syntax?); a quick scan of the rtic-syntax crate seems to indicate that `task_local` has been removed (?) and that `lock_free` still exists.

book: update the resources chapter

---

book/en/src/migration/migration_v5.md

migration/0.5: cover #[lock_free]

---

book/en/src/by-example/resources.md

for the "same priority requirement"; this prevents data races

book/resources: highlight that `#[lock_free]` includes a compile-time check

---

macros/src/codegen/module.rs

This allows tasks to be gated by `cfg` attributes when also using
monotonics. For example:
```rust
#[cfg(feature = "logging")]
#[task(shared = [logger])]
fn logger_init(mut cx: logger_init::Context) {
/* ... */
}
```
Without this change, the reschedule_at() implementation is
unconditionally included even though it references the SpawnHandle from
its task module, which is _conditionally_ included. This resulted in
compiler errors like the following:
```
error[E0433]: failed to resolve: use of undeclared crate or module `logger_init`
--> src/main.rs:243:8
|
243 |     fn logger_init(mut cx: logger_init::Context) {
|        ^^^^^^^^^^^ use of undeclared crate or module `logger_init`
```

Propogate the task attributes to the spawn handles

---

Cargo.toml
heterogeneous/Cargo.toml
heterogeneous/src/lib.rs
homogeneous/Cargo.toml
homogeneous/src/lib.rs
src/lib.rs

The trait `Nr`from crate `bare-metal` is deprecated in 1.0, and `cortex-m` moved to `InterruptNumber`, which new PACs are using. As a result, `cortex-m-rtic` does not compile when using newer PACs because the `Nr` trait is not implemented:
```
error[E0277]: the trait bound `Interrupt: Nr` is not satisfied
--> src/main.rs:7:1
|
7 | #[rtic::app(device = stm32wl::stm32wle5, peripherals = true)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Nr` is not implemented for `Interrupt`
|
= note: this error originates in the attribute macro `rtic::app` (in Nightly builds, run with -Z macro-backtrace for more info)
```
Older PACs that still use `Nr` will still work because `cortex_m` implements `Nr` for `InterruptNumber`. This was tested using the minimal code at …

Use cortex-m `InterruptNumber` instead of bare_metal `Nr`

---

macros/src/codegen/local_resources_struct.rs
macros/src/codegen/shared_resources_struct.rs

Continues the work started in #513

Silence rust-analyzer warnings on internal types

---

macros/src/codegen.rs
macros/src/codegen/dispatchers.rs
macros/src/codegen/local_resources.rs
macros/src/codegen/local_resources_struct.rs
macros/src/codegen/module.rs
macros/src/codegen/post_init.rs
macros/src/codegen/pre_init.rs
macros/src/codegen/shared_resources.rs
macros/src/codegen/shared_resources_struct.rs
macros/src/codegen/software_tasks.rs
macros/src/codegen/timer_queue.rs
macros/src/codegen/util.rs

Refactor so that all `idents` that had to call `mark_ident_internal` before now call `mark_name_internal` in the `util` module by default.
The commits can (and probably should) be squashed, they're separated for clarity.
Fixes #512

`mark_internal_ident` cleanup

---

Cargo.toml
src/lib.rs

It's not needed, since the user has to supply a PAC which will already depend on a suitable
cortex-m-rt version.
This allows using RTIC v0.5 with either cortex-m-rt 0.6 or 0.7.

v0.5: Remove cortex-m-rt dependency.

---

CHANGELOG.md
Cargo.toml
macros/Cargo.toml
macros/src/codegen/post_init.rs

`rtic-syntax` got the old multicore concept of `Locations` removed, see https://github.com/rtic-rs/rtic-syntax/pull/61
This updates `cortex-m-rtic` to match this

Release 0.6.0-rc.3 due to breaking change in rtic-syntax naming of shared and local

---

macros/src/codegen/shared_resources.rs
macros/src/codegen/shared_resources_struct.rs
macros/src/codegen/util.rs

Old error:
```
error[E0614]: type `value<'_>` cannot be dereferenced
--> examples/lock_minimal.rs:33:9
|
33 |         *c.shared.value += 1;
|         ^^^^^^^^^^^^^^^
```
New error:
```
error[E0614]: type `value_that_needs_to_be_locked<'_>` cannot be dereferenced
--> examples/lock_minimal.rs:33:9
|
33 |         *c.shared.value += 1;
|         ^^^^^^^^^^^^^^^
```

Better errors on when missing to lock shared resources

---

README.md

Remove rustc badge and requirements to edition 2018.

README: Remove rustc badge and Requirements

---

examples/locals.rs

I believe that is a typo s/shared/local_to_bar

Fix the locals.rs comment

---

book/en/src/by-example.md
book/en/src/by-example/resources.md

How examples are run never gets properly introduced before used in `by-example/resources.md`
Fixes #587

Highlight how to run examples locally

---

CHANGELOG.md
macros/Cargo.toml
macros/src/lib.rs

Seems over-engineered, but for projects where 
```
[build]
target-dir = "target"
```
is set to anything other than default `target` RTIC did simply not produce any `rtic-expansion.rs`.
This changes the approach to not giving up if not finding `target/` by looking at `OUT_DIR` and traversing back until `TARGET` is found.
As the `TARGET` target-triple variable is not available, approximate the `TARGET` folder (found in `target-dir`) with `s.starts_with("thumbv")`.
`target-dir` as set in `.cargo/config` will now be the parent directory of the `Path` ending with `TARGET`
```
cortex-m-rtic on  expansionoutdir [$!?] is 📦 v1.0.0 via R v1.58.0 took 4s
❯ cargo build --example spawn --target thumbv7em-none-eabihf
OUT_DIR
"/home/henrik/rust/rtic/cortex-m-rtic/target/thumbv7em-none-eabihf/debug/build …
```

RTIC macro expansion: Try to find target-dir

---

.github/workflows/build.yml
CHANGELOG.md

- Require clippy for deploy
- GHA: Automatic merge to release/vX
- Link dev-book to stable if they are describe the same release
- Update CHANGELOG
Development work is done in the master branch
Older versions previously were found in v0.5.x, v0.4.x branches.
Now with v1 released, and any breaking change forcing a v2,
a need to streamline documentation building arose.
The different docs:
- rtic.rs
- latest stable (v1)
- API documentation
- RTIC book
- old stable (v0.5)
- API documentation
- RTIC book
- oldold stable (v0.4)
- API documentation
- RTIC book
- docs.rs
- all previous crates.io releases
- API documentation
With this PR, when a pull request gets merged to master
with CI passing the current master branch gets merged
to `release/v$VERSION` where `$VERSION` is parsed from
cargo …

GHA: Automatic merge to release/vX

---

CHANGELOG.md
macros/src/codegen/hardware_tasks.rs
macros/src/codegen/idle.rs
macros/src/codegen/software_tasks.rs
src/lib.rs

Running cargo Clippy with pedantic rules denied
```
cargo clippy -- --deny clippy::pedantic
```
it will complain:
```
error: usage of wildcard import
|
16 | use rtic::mutex_prelude::*;
|     ^^^^^^^^^^^^^^^^^^^^^^ help: try: `rtic::mutex_prelude::{Mutex, TupleExt01, TupleExt02, TupleExt03, TupleExt04, TupleExt05, TupleExt06, TupleExt07, TupleExt08, TupleExt09, TupleExt10, TupleExt11, TupleExt12, TupleExt13, TupleExt14, TupleExt15, TupleExt16, TupleExt17, TupleExt18, TupleExt19, TupleExt20, TupleExt21, TupleExt22, TupleExt23, TupleExt24, TupleExt25, TupleExt26, TupleExt27, TupleExt28, TupleExt29, TupleExt30, TupleExt31, TupleExt32}`
|
= note: `-D clippy::wildcard-imports` implied by `-D clippy::pedantic`
= help: for further information visit …
```

rtic::mutex::prelude::* fixes glob import lint

---

src/export.rs

SYST::ptr has been deprecated in cortex-m v0.7.5
SYST::PTR is available since cortex-m v0.7.0
CI was failing due to a warning turned into an error by `deny(warnings)`

fix ci: use SYST::PTR

---

CHANGELOG.md
Cargo.toml
macros/Cargo.toml

Use the latest rtic-syntax, update the changelog with the last few undocumented releases

Bump rtic-syntax to v1.0.2 and fix Changelog

---

CHANGELOG.md
macros/src/codegen/local_resources.rs
macros/src/codegen/shared_resources.rs

This commit makes RTIC aware of user-provided `link_section` attributes,
letting user override default section mapping.

Allow custom `link_section` attributes for late resources

---

CHANGELOG.md
build.rs
macros/src/codegen/assertions.rs
macros/src/codegen/shared_resources.rs
macros/src/codegen/util.rs
src/export.rs

The basepri register appears to be aviable on thumbv8m.main but not thumbv8m.base. At the very least, attempting to compile against a Cortex-M23 based Microchip ATSAML10E16A generates an error:
```
error[E0432]: unresolved import `cortex_m::register::basepri`
--> /Users/dwatson/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-rtic-1.1.3/src/export.rs:25:5
|
25 | use cortex_m::register::basepri;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `basepri` in `register`
```
I wasn't sure if it made more sense to replace the `armv7m` config flag with something related to basepri availability or to get closer to matching the cortex-m use of several architecture specific flags. In the end i chose to make the minimal change possible and just narrowed the existing `thumbv8m` check.
Context: …

Remove use of basepri register on thumbv8m.base

---

.github/workflows/build.yml
CHANGELOG.md

actions-rs seems abandoned: See [link](https://github.com/actions-rs/toolchain/issues/216)
As GHA bundles rustup using it directly is trivial

CI: Run rustup and cargo directly

---

ui/task-priority-too-high.rs
ui/task-priority-too-high.stderr

NVIC prio bits must be in the range 1..=255: Handled by logical2hw()

---

CHANGELOG.md
examples/cfg-monotonic.rs
macros/src/codegen.rs
macros/src/codegen/module.rs
macros/src/codegen/post_init.rs
macros/src/codegen/software_tasks.rs
macros/src/codegen/timer_queue.rs

- Enable at least masking out a Monotonic
- Add example cfg-ing a Monotonic, showing limitations imposed by rtic-syntax
- Update changelog
The use case detailed in linked issue seems to be covered: Fixes #664

Basic cfg support, kind of, for Monotonics
